### ISSUE TITLE
please add vcdExtra to the vcd entry

### ISSUE THREAD

**Issue by friendly** [cran-task-views/TeachingStatistics#3]
Under related to books, you have

[vcd](https://cran.r-project.org/web/packages/vcd/index.html): Friendly, M. and Meyer, D. (2015), [Discrete Data Analysis with R](https://www.crcpress.com/Discrete-Data-Analysis-with-R-Visualization-and-Modeling-Techniques-for/Friendly-Meyer/p/book/9781498725835) , New York: Chapman and Hall/CRC. [Further resources](http://ddar.datavis.ca/) .

Please add [vcdExtra](https://cran.r-project.org/web/packages/vcdExtra/index.html) before the ':'

**Comment by paulnorthrop** [comment]
Many thanks, Michael.  This has been done.  Apologies for being slow!
