### ISSUE TITLE
Please add rqti package to Examination section

### ISSUE THREAD

**Issue by shevandrin** [cran-task-views/TeachingStatistics#4]
`r pkg("rqti")` crates exercises and exams in adherence to the QTI v2.1 standard directly from R. Users have the flexibility to render the exercises either locally (using qti.js) or integrate them seamlessly into the OPAL learning management system. Exercises can be created as R Markdown files or as rqti S4 classes. See also the [rqti homepage]( https://shevandrin.github.io/rqti/).

**Comment by paulnorthrop** [comment]
I have added package rqti. Thank you!
